CREATE DATABASE IF NOT EXISTS village_db DEFAULT CHARSET utf8mb4;
CREATE USER IF NOT EXISTS 'village'@'%' IDENTIFIED BY 'villagepass';
GRANT ALL PRIVILEGES ON village_db.* TO 'village'@'%';
FLUSH PRIVILEGES;
